# Nmae of the workflow
name: My Test Workflow

# Define the trigger events
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello, GitHub Actions!"

    # Job to build and test our C code
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:

        - name: Check out this repo # Use github actions checkout to check out this repo
          uses: actions/checkout@v3

        # Install necessary packages
        - name: Install dependencies
          run: sudo apt install -y build-essential python3
        - run: pwd

        # Runt our test
        - name: Run test
          run: python3 test.py
